# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TealiumAppsFlyerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumAppsFlyerExample
  pod 'TealiumAppsFlyer', :path=> '../'
  pod 'tealium-swift/Lifecycle', '~> 2.1'
  
end
