# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TealiumAppsFlyerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumAppsFlyerExample
  #!!!! Note: Change below to TealiumAppsflyer
  pod 't_a'
  pod 'tealium-swift/TealiumLogger'
  pod 'tealium-swift/TealiumTagManagement'
  pod 'tealium-swift/TealiumAppData'
  pod 'tealium-swift/TealiumDeviceData'
  pod 'tealium-swift/TealiumLifecycle'
end
