# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'TealiumAppsFlyerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumAppsFlyerExample
  pod 'TealiumAppsFlyer', :path=> '../'
  
  pod 'tealium-swift/Core', '~> 2.6'
  pod 'tealium-swift/TagManagement','~> 2.6'
  pod 'tealium-swift/Lifecycle', '~> 2.6'
  pod 'tealium-swift/RemoteCommands', '~> 2.6'

end
